name: Add Numbers Workflow

on:
  workflow_call:
    inputs:
      number1:
        description: 'First number'
        required: true
        type: number
        default: 0
      number2:
        description: 'Second number'
        required: true
        type: number
        default: 0
    outputs:
      sum:
        description: 'Sum of the two numbers'
        value: ${{ jobs.add-numbers.outputs.sum }}
        

jobs:
  add-numbers:
    name: Add two numbers
    runs-on: ubuntu-latest

    outputs:
      sum: ${{ steps.calculate.outputs.sum }}
    
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v2
        
      - id: set-up-env
        name: Set up environment
        run: |
          echo "NUMBER1=${{ github.event.inputs.number1 }}" >> $GITHUB_ENV
          echo "NUMBER2=${{ github.event.inputs.number2 }}" >> $GITHUB_ENV
          
      - name: Calculate sum
        id: calculate
        run: |
          sum=$((NUMBER1 + NUMBER2))
          echo "SUM=${sum}" >> $GITHUB_OUTPUT
          
