name: Test workflow

on: 
  workflow_dispatch:

jobs:
  test:
    strategy:
        matrix:
          number1: [1, 2, 3, 4, 5, 6, 7]
          number2: [7, 6, 5, 4, 3, 2, 1]
    uses: krharsh17/reusable-workflows/.github/workflows/add.yaml@main
    with:
      number1: ${{ matrix.number1 }}
      number2: ${{ matrix.number2 }}   
