name: Test workflow

on: 
  workflow_dispatch:

jobs:
  test:
    uses: krharsh17/reusable-workflows/.github/workflows/add.yaml@main
    with:
      number1: 4
      number2: 5

  print:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{ needs.test.outputs.sum }}

    
